=== heavenchou/xml_p4/dtd/cbetaxml.dtd
<!-- CBETA project DTD, generated with FRED 31.12.98  (CW)

converted to XML form 2.1.99 (CW)

-->
<!--  A TEI document is a text preceded by a TEI header.       -->
<!ELEMENT TEI.2 (teiHeader, text)>
<!ELEMENT teiHeader 
	(fileDesc, encodingDesc*, profileDesc*, revisionDesc?) >
<!ELEMENT fileDesc (titleStmt, (editionStmt)?, (extent)?, publicationStmt, (sourceDesc)+)>
<!ELEMENT titleStmt (((title)+, (author | respStmt)*))>
<!ELEMENT editionStmt (edition)>
<!ELEMENT edition (#PCDATA | date)*>
<!ELEMENT extent (#PCDATA | address | date | name | corr | gloss | term | title | ref | xref | anchor)*>
<!ATTLIST extent
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "extent"
>
<!--  5.2.4:  The publication statement                        -->
<!ELEMENT publicationStmt (distributor, availability, date)>
<!ELEMENT distributor (name+, address)>
<!ELEMENT availability (p)>
<!--  5.2.7:  The source description                           -->
<!ELEMENT sourceDesc (bibl+, p?)>
<!--  5.3:  The encoding description                           -->
<!ELEMENT encodingDesc (projectDesc, witList?)>
<!--  5.3.1:  The project description                          -->
<!ELEMENT projectDesc (p+)>
<!--  5.4 The Profile Description -->
<!ELEMENT profileDesc 
	(creation?, langUsage*, textClass*) >
<!ATTLIST profileDesc 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "profileDesc" >
<!ELEMENT creation 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST creation 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "creation" >

<!ELEMENT langUsage 
	(p | language)+ >
<!ATTLIST langUsage 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	default (YES | NO) "NO"
	TEIform CDATA "langUsage" >

<!ELEMENT language 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST language 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	wsd ENTITY #IMPLIED
	usage CDATA #IMPLIED
	TEIform CDATA "language" >

<!ELEMENT textClass 
	(classCode | catRef | keywords)* >
<!ATTLIST textClass 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	default (YES | NO) "NO"
	TEIform CDATA "textClass" >

<!ELEMENT keywords 
	(term+ | list) >
<!ATTLIST keywords 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	scheme IDREF #IMPLIED
	TEIform CDATA "keywords" >

<!ELEMENT classCode 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST classCode 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	scheme IDREF #IMPLIED
	TEIform CDATA "classCode" >

<!ELEMENT catRef 
	EMPTY >
<!ATTLIST catRef 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	target IDREFS #REQUIRED
	scheme IDREF #IMPLIED
	TEIform CDATA "catRef" >
	
<!--  5.5:  The Revision Description                           -->
<!ELEMENT revisionDesc (change)+>
<!ELEMENT change (date, respStmt, item)>
<!--  6.1:  Paragraph                                          -->
<!ELEMENT p (#PCDATA | anchor | app | corr | fan | figure | foreign | gaiji | l | lb | note | pb | sic | skgloss | span | table | term | tt)*>
<!ATTLIST p
	id ID #IMPLIED
	n CDATA #IMPLIED
	loc CDATA #IMPLIED
	lang CDATA #IMPLIED
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT foreign 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | eg | bibl | biblFull | figure | cit | q | label 
	| list | listBibl | note | stage | table | text | anchor 
	| gap | index | interp | interpGrp | lb | milestone | pb | gaiji)* >
<!ATTLIST foreign 
	cert CDATA #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
	resp CDATA #IMPLIED
	TEIform CDATA "foreign" >

<!--  6.3.4:  Highlighted phrases (cont'd)                     -->
<!ELEMENT term (#PCDATA | gaiji | lb | pb | app | fan | l)*>
<!ATTLIST term
	rend CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!-- GLOSS is from the TEI set, but the attribute alt has been added (CW, 18.11.98) -->
<!ELEMENT gloss (#PCDATA | corr | gaiji | skgloss)*>
<!ATTLIST gloss
	n CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!-- SKGLOSS is added by CBETA -->
<!ELEMENT skgloss (gloss, term)>
<!ATTLIST skgloss
	n CDATA #IMPLIED
>
<!--  6.4.1:  Proper Nouns                                     -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!--  6.4.2:  Addresses and their components                   -->
<!ELEMENT address (addrLine)>
<!ELEMENT addrLine (#PCDATA)>
<!--  6.4.4:  Dates and times                                  -->
<!ELEMENT date (#PCDATA)>
<!--  6.5.1:  Editorial tags for correction                    -->
<!-- CORR is from the TEI set, but the attributes cf1, cf2 has been added (CW, 1.7.98) -->
<!ELEMENT corr (#PCDATA | gaiji | xref | anchor | lb | note | term)*>
<!ATTLIST corr
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	resp CDATA #IMPLIED
	cert CDATA #IMPLIED
	sic CDATA #IMPLIED
>
<!ELEMENT sic (#PCDATA | app | corr | gaiji | head | xref | anchor | l | lb | note | p | pb | sic | term)*>
<!ATTLIST sic
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	resp CDATA #IMPLIED
	cert CDATA #IMPLIED
	corr CDATA #IMPLIED
	n CDATA #IMPLIED
>

<!--  6.6:  Simple cross references                            -->
<!ELEMENT ref (#PCDATA | address | date | name | corr | gloss | term | title | ref | xref | anchor | bibl | list | note | figure | table | text)*>
<!ATTLIST ref
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	type CDATA #IMPLIED
	resp CDATA #IMPLIED
	crdate CDATA #IMPLIED
	targType CDATA #IMPLIED
	targOrder (Y | N | U) "U"
	evaluate (all | one | none) #IMPLIED
	target IDREFS #IMPLIED
	TEIform CDATA "ref"
>
<!--  6.7:  Lists and List Items                               -->
<!-- <!ELEMENT list (head?, (item | gaiji | lb | milestone | pb)*)> -->
<!ELEMENT list (#PCDATA | anchor | app | head | item | gaiji | lb | milestone | note | pb)*>
<!ATTLIST list
	id ID #IMPLIED
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT item (#PCDATA | anchor | byline | figure | gaiji | lb | list | app | pb | corr | note | p | ref | sic | title)*>
<!ATTLIST item
	id ID #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT head (#PCDATA | app | skgloss | corr | foreign | gaiji | lb | pb | note | anchor | title | l | sic | tt)*>
<!ATTLIST head
	rend CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!--  6.8.1:  Annotation                                       -->
<!ELEMENT note (#PCDATA | anchor | app | figure | p | corr | foreign | gaiji | note | skgloss | gloss | term | lb | list | pb | lg | l | fan | sic | tt | todo | xref)*>
<!ATTLIST note
	n CDATA #IMPLIED
	lang CDATA #IMPLIED
	resp CDATA #IMPLIED
	type CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!--  6.9.3:  Milestone tags  -->
<!ELEMENT pb EMPTY>
<!ATTLIST pb
	ed CDATA #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT milestone EMPTY>
<!ATTLIST milestone
	id ID #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	ed CDATA #IMPLIED
	n CDATA #IMPLIED
	unit CDATA #REQUIRED
	TEIform CDATA "milestone"
>
<!ELEMENT lb EMPTY>
<!ATTLIST lb
	id ID #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	ed CDATA #IMPLIED
	n CDATA #IMPLIED
	TEIform CDATA "lb"
>
<!--  6.10.1:  Tags for Bibliographic References               -->
<!ELEMENT bibl (#PCDATA)>
<!ATTLIST bibl
	lang CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | anchor | gaiji | app | foreign | note | lb | pb | sic | skgloss | corr | tt)*>
<!ATTLIST title
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!ELEMENT respStmt (resp | name)*>
<!ELEMENT resp (#PCDATA)>
<!--  6.10.2.2:  Tags for Bibliographic References (cont'd)    -->
<!ELEMENT author (#PCDATA | address | date | name | corr | gaiji | gloss | term | title | ref | xref | anchor)*>
<!ATTLIST author
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "author"
>
<!--  6.11.1:  Verse                                           -->
<!ELEMENT l (#PCDATA | gaiji | skgloss | corr | app | figure | foreign | note | lb | pb | sic | term | tt | anchor)*>
<!ATTLIST l
	rend CDATA #IMPLIED
>
<!ELEMENT lg (#PCDATA | gaiji | lb | l | pb | app | anchor | skgloss | gloss | term | head | p | note | sic | tt )*>
<!ATTLIST lg
	id ID #IMPLIED
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!--  7:  Top-level parts of default structure                 -->
<!ELEMENT text (body)>
<!ATTLIST text
	rend CDATA #IMPLIED
>
<!ELEMENT body (app | gaiji | lb | pb | head | juan | byline | div1 | milestone | mulu | note)*>

<!--  7.1.2:  Numbered divisions                               -->
<!ELEMENT div1 (#PCDATA | div2 | head | p | lg | juan | gaiji | lb | pb | byline | trailer | app | list | anchor | corr | mulu | xref | milestone | note | tt)*>
<!ATTLIST div1
	type CDATA #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT div2 (#PCDATA | div3 | anchor | app | byline | figure | gaiji | head | jhead | juan | lb | lg | list | milestone | mulu | note | p | pb | trailer | xref | tt)*>
<!ATTLIST div2
	type CDATA #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT div3 (#PCDATA | div4 | anchor | head | p | lg | milestone | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | qa | mulu | xref | tt)*>
<!ATTLIST div3
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div4 (#PCDATA | div5 | anchor | head | p | lg | milestone | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | qa | mulu | tt| xref)*>
<!ATTLIST div4
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div5 (#PCDATA | div6 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div5
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div6 (#PCDATA | div7 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div6
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div7 (#PCDATA | div8 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | milestone | mulu | tt)*>
<!ATTLIST div7
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div8 (#PCDATA | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div8
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!--  7.2.4:  Tags for start and end of divisions              -->
<!ELEMENT trailer (#PCDATA | anchor | gaiji | lb | corr | app | title | pb | note | head)*>
<!ELEMENT byline (#PCDATA | app | gaiji | lb | pb | corr | foreign | note | anchor | sic | tt)*>
<!ATTLIST byline
	type CDATA #IMPLIED
>
<!--  14.2.1:  Extended pointers                               -->
<!-- XREF is from the TEI set, but the attributes loc, rend has been added (Chou, Ray, 2000/9/5 10:18AM) -->
<!ELEMENT xref (#PCDATA | anchor | app | lb | note)*>
<!ATTLIST xref
	doc CDATA #IMPLIED
	loc CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!--  14.3:  Segments and Anchors                              -->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
	id ID #IMPLIED
	n CDATA #IMPLIED
>
<!--  22:  Tables, Formulae, Figures                           -->
<!--  22.1.1:  Tables                                          -->
<!ELEMENT table ((head)*, (row)+)>
<!ATTLIST table
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	TEIform CDATA "table"
>
<!ELEMENT row ((cell | table)+)>
<!ATTLIST row
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	role CDATA "data"
	TEIform CDATA "row"
>
<!ELEMENT cell (#PCDATA | app | address | date | name | corr | gloss | term | title | ref | xref | anchor | bibl | list | note | figure | sic | table | text | pb | lb | gaiji)*>
<!ATTLIST cell
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	role CDATA "data"
	rows CDATA "1"
	cols CDATA "1"
	TEIform CDATA "cell"
>
<!--  22.3:  Figures  -->
<!ELEMENT figure EMPTY>
<!ATTLIST figure
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	entity ENTITY #IMPLIED
	TEIform CDATA "figure"
>
<!ELEMENT app (lem?, rdg+)>
<!-- type, source attributes are added by Ray -->
<!ATTLIST app
	type CDATA #IMPLIED
	source CDATA #IMPLIED
	wit CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	yuan CDATA #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	word-count CDATA #IMPLIED
	TEIform CDATA "app"
>
<!ELEMENT lem (#PCDATA | anchor | app | div1 | div2 | figure | gaiji | item | lb | milestone | byline | note | l | pb | skgloss | lg | fan | foreign | head | p | juan | title | list | corr | mulu | sic | term | tt | xref )*>
<!ATTLIST lem
	wit CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	resp CDATA #IMPLIED
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	TEIform CDATA "lem"
>

<!ELEMENT rdg (#PCDATA | figure | gaiji | lb | note | fan | p | todo)*>
<!-- resp attribute is added by CBETA -->
<!ATTLIST rdg
	type CDATA #IMPLIED
	cf1 CDATA #IMPLIED
	wit CDATA #IMPLIED
	resp CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "rdg"
>
<!ELEMENT span (#PCDATA | gaiji | lb | app | pb)*>
<!ATTLIST span
	id ID #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!-- CBETA specific elements -->
<!ELEMENT witList (witness)+>
<!ELEMENT witness (#PCDATA | note)*>
<!ATTLIST witness
	sigil CDATA #IMPLIED
	included CDATA #IMPLIED
>
<!ELEMENT jhead (#PCDATA | app | corr | foreign | gaiji | lb | pb | note | anchor | sic | skgloss | title | tt)*>
<!ATTLIST jhead
	type CDATA #IMPLIED
>
<!ELEMENT juan (#PCDATA | anchor | skgloss | app | corr | gaiji | lb | pb | note | jhead | head | byline | title | mulu)*>
<!ATTLIST juan
	fun CDATA #IMPLIED
	n CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT fan (#PCDATA | anchor | zi | yin)*>
<!ELEMENT zi (#PCDATA | anchor | app | lb | note | gaiji | sic | yin)*>
<!ELEMENT sg (#PCDATA | anchor | app | note | gaiji | corr | lb | sic)*>
<!ATTLIST sg
	type CDATA #IMPLIED
>
<!ELEMENT yin (#PCDATA | anchor | app | lb | note | gaiji | zi | sg)*>
<!ATTLIST yin
	yuan CDATA #IMPLIED
>
<!ELEMENT gaiji (#PCDATA)>
<!ATTLIST gaiji
	id ID #IMPLIED
	mojikyo CDATA #IMPLIED
	mofont CDATA #IMPLIED
	mochar CDATA #IMPLIED
	cb CDATA #IMPLIED
	des CDATA #IMPLIED
	uni CDATA #IMPLIED
	nor CDATA #IMPLIED
	sdchar CDATA #IMPLIED
	big5 CDATA #IMPLIED
	cbdia CDATA #IMPLIED
	udia CDATA #IMPLIED
	cx CDATA #IMPLIED
>
<!ELEMENT mulu (#PCDATA)>
<!ATTLIST mulu
	id ID #IMPLIED
	type CDATA #IMPLIED
	level CDATA #IMPLIED
	n CDATA #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT tt (#PCDATA | anchor | t | lb)*>
<!ATTLIST tt
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	n CDATA #IMPLIED
	word-count CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT t (#PCDATA | corr | foreign | gaiji | yin | app | note | lb | l | lg | anchor | pb | sic | title)*>
<!ATTLIST t
	lang CDATA #IMPLIED
	place CDATA #IMPLIED
	repeat CDATA #IMPLIED
	resp CDATA #IMPLIED
	rend CDATA #IMPLIED
	cert CDATA #IMPLIED
>

<!ELEMENT todo EMPTY>
<!ATTLIST todo
	type CDATA #IMPLIED
>

<!ELEMENT qa (answer | lb | question)*>
<!ELEMENT question (#PCDATA|lb|p)*>
<!ELEMENT answer (#PCDATA|lb|p)*>

<!-- Notations -->
<!NOTATION doc SYSTEM "uedit32.exe">
<!NOTATION GIF SYSTEM "acdsee32.exe">

=== heavenchou/xml_p4/T17/T17n0846.xml
<?xml version="1.0" encoding="big5" ?><!-- -*- coding: big5-dos -*- -->
<?xml-stylesheet type="text/xsl" href="../dtd/cbeta.xsl" ?>
<!DOCTYPE TEI.2 SYSTEM "../dtd/cbetaxml.dtd"
[<!ENTITY % ENTY  SYSTEM "T17n0846.ent" >
<!ENTITY % CBENT  SYSTEM "../dtd/cbeta.ent" >
<!ENTITY % JAP  SYSTEM "../dtd/jap.ent" >
%ENTY;
%CBENT;
%JAP;
]>
<TEI.2>
<teiHeader>
	<fileDesc>
		<titleStmt>
			<title>Taisho Tripitaka, Electronic version, No. 0846 外道問聖大乘法無我義經</title>
			<author>宋 法天譯</author>
			<respStmt>
				<resp>Electronic Version by</resp>
				<name>CBETA</name>
			</respStmt>
		</titleStmt>
	<editionStmt>
		<edition>$Revision: 1.6 $ (Big5)<date>$Date: 2004/09/11 10:12:46 $</date></edition>
	</editionStmt>
	<extent>1卷</extent>
	<publicationStmt>
		<distributor>
			<name>中華電子佛典協會 (CBETA)</name>
			<address>
				<addrLine>service@cbeta.org</addrLine>
			</address>
		</distributor>
		<availability>
			<p>Available for non-commercial use when distributed with this header intact.</p>
		</availability>
		<date>$Date: 2004/09/11 10:12:46 $</date>
	</publicationStmt>
	<sourceDesc>
		<bibl>Taisho Tripitaka Vol. 17, No. 846 &desc;</bibl>
	</sourceDesc>
</fileDesc>
<encodingDesc>
	<projectDesc>
		<p type="ly" lang="eng">Text as provided by Mr. Hsiao Chen-Kuo, Tripitaka Koreana as provided by Mr. Christian Wittern, Text as inputted by Mr. Yan Hsue-Hsin, Text as provided by Anonymous, USA</p>
		<p type="ly" lang="chi">蕭鎮國大德提供，維習安大德提供之高麗藏 CD 經文，閻學新大德輸入，北美某大德提供</p>
	</projectDesc>
</encodingDesc>
<profileDesc>
		<langUsage>
			<language id="eng">English</language>
			<language id="chi">Chinese</language>
		</langUsage>
	</profileDesc>
	<revisionDesc>
	<change>
		<date>19991012/10:16:44</date>
		<respStmt><name>CW</name><resp>ed.</resp></respStmt>
		<item>Created initial TEI XML version with BASICX.BAT (99/10/12)</item>
	</change>
<!--
$Log: T17n0846.xml,v $
Revision 1.6  2004/09/11 10:12:46  saywhat
刪除空的 juan close

Revision 1.5  2004/05/11 14:39:04  saywhat
修訂經號的<head> → <head type="no">

Revision 1.4  2004/04/20 08:38:30  maha
「版本日期」標記修訂

Revision 1.3  2004/01/02 05:53:38  maha
<note mod>裡的corr2app

Revision 1.2  2003/06/26 02:49:43  saywhat
<corr>→<app>

Revision 1.1.1.1  2003/05/05 04:09:05  ray
recover cvs

Revision 1.15  2002/12/05 06:38:03  saywhat
校勘插入處理

Revision 1.14  2002/11/04 10:43:50  ray
tei.2 => TEI.2

Revision 1.13  2002/07/29 09:55:37  vinking
modified lang

Revision 1.12  2002/04/04 09:05:01  ray
xml:stylesheet => xml-stylesheet

Revision 1.11  2001/07/27 07:12:22  ray
去除多餘的 <author>

Revision 1.10  2001/07/24 06:52:08  ray
add 作者、譯者 <author> 卷數 <extent>

Revision 1.9  2001/05/25 08:57:30  ray
經號統一為四碼

Revision 1.8  2001/03/30 05:47:16  ray
缺字CB碼由四碼增長為五碼

Revision 1.7  2001/03/25 09:07:26  ray
add <milestone>

Revision 1.6  2001/02/07 06:52:52  chris
Fixed problem with comment in the previous checkin

Revision 1.5  2001/02/03 07:42:31  chris
Added keywords $Revision: 1.6 $, $Date: 2004/09/11 10:12:46 $ and $Log.
Added comment  for Emacs

-->
 </revisionDesc>
</teiHeader>
<text><body>
<lb n="0934a13"/>
<milestone unit="juan" n="1"/>
<lb n="0934a14"/>
<lb n="0934a15"/><head type="no">No. 846</head>
<lb n="0934a16"/><juan fun="open" n="001"><mulu type="卷" n="001"/><jhead><title>外道問聖大乘法無我義經</title></jhead></juan>
<lb n="0934a17"/>
<lb n="0934a18"/><byline type="Translator"><note n="0934001" resp="Taisho" type="orig" place="foot text">（宋）＋西【明】，（（西天…譯））二十四字＝（（三藏傳教大師臣法天奉詔譯））十二字【宮】</note><note n="0934001" resp="CBETA" type="mod">（宋）＋西【明】，（西天譯經三藏朝散大夫試鴻臚少卿傳教大師臣法天奉詔譯）二十<app><lem resp="CBETA.say">五</lem><rdg wit="【大】">四</rdg></app>字＝（三藏傳教大師臣法天奉詔譯）十二字【宮】</note><app n="0934001"><lem>西天<note n="0934002" resp="Taisho" type="orig" place="foot text">〔譯經〕－【明】</note><app n="0934002"><lem>譯經</lem><rdg wit="【明】" resp="Taisho">&lac;</rdg></app>三藏朝散大夫
<lb n="0934a19"/>試鴻臚少卿傳教大師<note n="0934003" resp="Taisho" type="orig" place="foot text">〔臣〕－【明】</note><app n="0934003"><lem>臣</lem><rdg wit="【明】" resp="Taisho">&lac;</rdg></app>
<lb n="0934a20"/>法天奉　詔譯</lem><rdg wit="【宮】" resp="Taisho">三藏傳教大師臣法天奉詔譯</rdg><rdg wit="【明】" resp="Taisho">宋西天譯經三藏朝散大夫試鴻臚少卿傳教大師臣法天奉詔譯</rdg></app></byline>
<lb n="0934a21"/><div1 type="jing"><p>如是我聞。一時佛在大眾中。爾時外道。有疑
<lb n="0934a22"/>欲決。迷大乘行。來至佛所。稽首恭重。合十指
<lb n="0934a23"/>掌。問無我義。大丈夫。是一切智。常說此身無
<lb n="0934a24"/>我。若身無我本性亦無。云何說有哀啼戲笑
<lb n="0934a25"/>憎愛兩舌等事。當何所生。是我所疑。願賜除
<lb n="0934a26"/><note n="0934004" resp="Taisho" type="orig" place="foot text">〔斷〕－【宋】【元】</note><app n="0934004"><lem>斷</lem><rdg wit="【宋】【元】" resp="Taisho">&lac;</rdg></app></p>
<lb n="0934a27"/><p>如來所言。身與本性。有無云何。佛言外道。諦
<lb n="0934a28"/>聽諦受。當為汝說</p>
<lb n="0934a29"/><p>佛言。身與本性。體本空故。說或有或無。斯成
<pb ed="T" id="T17.0846.0934b" n="0934b"/>
<lb n="0934b01"/>二法。言是有者。斯更虛妄。佛言。<note n="0934005" resp="Taisho" type="orig" place="foot text">當觀＝觀當【宋】</note><app n="0934005"><lem>當觀</lem><rdg wit="【宋】" resp="Taisho">觀當</rdg></app>全身
<lb n="0934b02"/>髮甲皮毛。兩手雙足。至於脂筋脾腸骨髓等
<lb n="0934b03"/>事。周遍內外。不見本性。外道言大丈夫。若彼
<lb n="0934b04"/>不見本性。以我肉眼云何能見。或以天眼而
<lb n="0934b05"/>能見乎。佛言。天眼見彼。無色無相無住。此見
<lb n="0934b06"/>非見。外道言。若如是說。大聖妄語。若彼非
<lb n="0934b07"/>者。云何現見有此啼笑嬉戲瞋怒憎愛兩舌
<lb n="0934b08"/>等事。以如是故。何得說無。又說或有或無。斯
<lb n="0934b09"/>成二義。又言。大丈夫。若彼有無不得說者。云
<lb n="0934b10"/>何說言彼有所著。彼無所著。又言空者當何
<lb n="0934b11"/>所如。佛言。如是如是。空非所如。體不可得
<lb n="0934b12"/>故。外道言。若此者笑哭嬉戲瞋<note n="0934006" resp="Taisho" type="orig" place="foot text">怒＝恕【宋】</note><app n="0934006"><lem>怒</lem><rdg wit="【宋】" resp="Taisho">恕</rdg></app>憎愛兩舌
<lb n="0934b13"/>等事。當何所見。佛言。如夢如幻如化。如影像
<lb n="0934b14"/>相。外道言。云何夢相。云何幻化相。云何影像
<lb n="0934b15"/>相。佛言。幻化非相。空非執持。夢本體空。如
<lb n="0934b16"/>陽焰故。影像無色。虛假不實。如是所見。乃至
<lb n="0934b17"/>一切事。皆如幻如化。如夢如影。當如是見</p>
<lb n="0934b18"/><p>復次有二種見。莊嚴真如。彼莊嚴者。此即名
<lb n="0934b19"/>我。此即名他。是名人補特伽羅。名人世間思
<lb n="0934b20"/>惟。至於資財。男女兄弟。妻妾等名。心所思惟
<lb n="0934b21"/>莊嚴。彼如是法。無自無他。無人無命。無補特
<lb n="0934b22"/>伽羅。無有情。無世間。無見者。無資財。無男
<lb n="0934b23"/>女。無朋友。無妻妾等。彼一切事不見自性。云
<lb n="0934b24"/>何彼出世間。莊嚴果報。善惡生滅。彼真如莊
<lb n="0934b25"/>嚴果報。無善無惡。不生不滅。無煩惱。無快樂。
<lb n="0934b26"/>而彼諸法各各如是。又彼世間及出世間。二
<lb n="0934b27"/>種莊嚴。令諸有情因莊嚴故。而生煩惱處於
<lb n="0934b28"/>輪迴。久久展轉不知真如。彼知<note n="0934007" resp="Taisho" type="orig" place="foot text">法＝泫【宋】</note><app n="0934007"><lem>法</lem><rdg wit="【宋】" resp="Taisho">泫</rdg></app>者思惟莊
<lb n="0934b29"/>嚴。疑此苦受彼苦受惡。遠離解脫而不見道。
<pb ed="T" id="T17.0846.0934c" n="0934c"/>
<lb n="0934c01"/>愚癡有情以迷執故。輪轉生死墮於惡趣。行
<lb n="0934c02"/>世間法不見真如。盡彼輪迴<note n="0934008" resp="Taisho" type="orig" place="foot text">由＝猶【元】【明】</note><app n="0934008"><lem>由</lem><rdg wit="【元】【明】" resp="Taisho">猶</rdg></app>如織網。用線
<lb n="0934c03"/>展轉復去復來。又如日月二種行往。晝夜隱
<lb n="0934c04"/>顯出沒世間。諸行無常不久破壞。輪轉生死
<lb n="0934c05"/>來往亦然。而真如體離莊嚴句。又彼天人乾
<lb n="0934c06"/>闥婆等。及彼女等住<note n="0934009" resp="Taisho" type="orig" place="foot text">於＝彼【明】</note><app n="0934009"><lem>於</lem><rdg wit="【明】" resp="Taisho">彼</rdg></app>天上。<note n="0934010" resp="Taisho" type="orig" place="foot text">以＝次【三】</note><note n="0934010" resp="CBETA" type="mod">以＝次【宋】【元】【明】</note><app n="0934010"><lem>以</lem><rdg wit="【宋】【元】【明】" resp="Taisho">次</rdg></app>彼莊嚴果
<lb n="0934c07"/>報。墮一切有。復有持明成就。夜叉緊那羅。摩
<lb n="0934c08"/>&CB00264;羅<note n="0934011" resp="Taisho" type="orig" place="foot text">伽＝加【明】</note><app n="0934011"><lem>伽</lem><rdg wit="【明】" resp="Taisho">加</rdg></app>。彼以一切莊嚴果報。復墮地獄惡精
<lb n="0934c09"/>進天。以彼神通而作功德。以彼一切莊嚴果
<lb n="0934c10"/>報。或墮彼天。又若帝釋及轉輪王。具最上德
<lb n="0934c11"/>及最上句。以彼一切莊嚴果報。復生傍生。智
<lb n="0934c12"/>者於一切時。宜應遠離天上最上大樂。&M010527;觀
<lb n="0934c13"/>菩提之心。靈明廓<note n="0934012" resp="Taisho" type="orig" place="foot text">澈＝徹【元】【明】</note><app n="0934012"><lem>澈</lem><rdg wit="【元】【明】" resp="Taisho">徹</rdg></app>。無自性。無罣礙。亦無
<lb n="0934c14"/>所住。一切皆空。亦復遠離一切戲論。外道。菩
<lb n="0934c15"/>提心相。不硬不軟。不熱不冷。無觸無執。又菩
<lb n="0934c16"/>提心相。非長非短。不圓不方。不肥不瘦。又菩
<lb n="0934c17"/>提心相。不白不黑。不赤不黃。非色非相。彼菩
<lb n="0934c18"/>提心。不作相非顯耀。無性無纏縛。由如虛空
<lb n="0934c19"/>而無色故。菩提心相而離觀察。外道。而汝不
<lb n="0934c20"/>知菩提心相與般若波羅蜜多而相應故。又
<lb n="0934c21"/>菩提心相。自性清淨。無物無喻。不可&CB00418;視。是
<lb n="0934c22"/>最上句。又菩提心相。非諸物像。無相似者。如
<lb n="0934c23"/>水成漚。雖&CB00418;非有。如幻化如陽焰。喻如泥團
<lb n="0934c24"/>作諸坯器。眾名雖具咸成戲論。貪瞋癡等亦
<lb n="0934c25"/>幻化有。一味空故。如電之住剎那不見。觀彼
<lb n="0934c26"/>般若波羅蜜多。及作諸善。亦復如是。至於談
<lb n="0934c27"/>笑嬉戲。歌舞歡樂。飲食愛欲。一切如夢。有情
<lb n="0934c28"/>諸行畢竟體空。心喻虛空。疑當何立。行般若
<lb n="0934c29"/>行。&M010527;若此觀了一切性。自然解脫。得最上句
<pb ed="T" id="T17.0846.0935a" n="0935a"/>
<lb n="0935a01"/>諸佛所說。無上菩提由斯生出。當作是觀。作
<lb n="0935a02"/>此觀者得最上涅槃。乃至往昔造作諸過。咸
<lb n="0935a03"/>悉除<note n="0935001" resp="Taisho" type="orig" place="foot text">滅＝減【明】</note><app n="0935001"><lem>滅</lem><rdg wit="【明】" resp="Taisho">減</rdg></app>生無量德。而於此生不染諸過。專精
<lb n="0935a04"/>觀行決定成就。若與真如不相應者。應念非
<lb n="0935a05"/>真如&CB00057;及金剛鈴真如無生印。而起真如相
<lb n="0935a06"/>應之行。決定圓滿如上功德</p>
<lb n="0935a07"/><p>爾時外道聞是語已審諦觀<app><lem>察</lem><rdg wit="【大】">際</rdg></app>。而彼疑<note n="0935002" resp="Taisho" type="orig" place="foot text">綱＝網【三】【宮】</note><note n="0935002" resp="CBETA" type="mod">綱＝網【宋】【元】【明】【宮】</note><app n="0935002"><lem>綱</lem><rdg wit="【宋】【元】【明】【宮】" resp="Taisho">網</rdg></app>皆
<lb n="0935a08"/>悉除斷。作是觀已獲住大乘。瞻奉歡喜作禮
<lb n="0935a09"/>而退</p>
<lb n="0935a10"/><trailer><title>外道問聖<note n="0935003" resp="Taisho" type="orig" place="foot text">大乘＋（法）【明】</note><app n="0935003"><lem>大乘</lem><rdg wit="【明】" resp="Taisho">大乘法</rdg></app>無我義經</title></trailer></div1>
</body></text></TEI.2>
