=== heavenchou/xml_p4/dtd/cbetaxml.dtd
<!-- CBETA project DTD, generated with FRED 31.12.98  (CW)

converted to XML form 2.1.99 (CW)

-->
<!--  A TEI document is a text preceded by a TEI header.       -->
<!ELEMENT TEI.2 (teiHeader, text)>
<!ELEMENT teiHeader 
	(fileDesc, encodingDesc*, profileDesc*, revisionDesc?) >
<!ELEMENT fileDesc (titleStmt, (editionStmt)?, (extent)?, publicationStmt, (sourceDesc)+)>
<!ELEMENT titleStmt (((title)+, (author | respStmt)*))>
<!ELEMENT editionStmt (edition)>
<!ELEMENT edition (#PCDATA | date)*>
<!ELEMENT extent (#PCDATA | address | date | name | corr | gloss | term | title | ref | xref | anchor)*>
<!ATTLIST extent
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "extent"
>
<!--  5.2.4:  The publication statement                        -->
<!ELEMENT publicationStmt (distributor, availability, date)>
<!ELEMENT distributor (name+, address)>
<!ELEMENT availability (p)>
<!--  5.2.7:  The source description                           -->
<!ELEMENT sourceDesc (bibl+, p?)>
<!--  5.3:  The encoding description                           -->
<!ELEMENT encodingDesc (projectDesc, witList?)>
<!--  5.3.1:  The project description                          -->
<!ELEMENT projectDesc (p+)>
<!--  5.4 The Profile Description -->
<!ELEMENT profileDesc 
	(creation?, langUsage*, textClass*) >
<!ATTLIST profileDesc 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "profileDesc" >
<!ELEMENT creation 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST creation 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "creation" >

<!ELEMENT langUsage 
	(p | language)+ >
<!ATTLIST langUsage 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	default (YES | NO) "NO"
	TEIform CDATA "langUsage" >

<!ELEMENT language 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST language 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	wsd ENTITY #IMPLIED
	usage CDATA #IMPLIED
	TEIform CDATA "language" >

<!ELEMENT textClass 
	(classCode | catRef | keywords)* >
<!ATTLIST textClass 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	default (YES | NO) "NO"
	TEIform CDATA "textClass" >

<!ELEMENT keywords 
	(term+ | list) >
<!ATTLIST keywords 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	scheme IDREF #IMPLIED
	TEIform CDATA "keywords" >

<!ELEMENT classCode 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST classCode 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	scheme IDREF #IMPLIED
	TEIform CDATA "classCode" >

<!ELEMENT catRef 
	EMPTY >
<!ATTLIST catRef 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	target IDREFS #REQUIRED
	scheme IDREF #IMPLIED
	TEIform CDATA "catRef" >
	
<!--  5.5:  The Revision Description                           -->
<!ELEMENT revisionDesc (change)+>
<!ELEMENT change (date, respStmt, item)>
<!--  6.1:  Paragraph                                          -->
<!ELEMENT p (#PCDATA | anchor | app | corr | fan | figure | foreign | gaiji | l | lb | note | pb | sic | skgloss | span | table | term | tt)*>
<!ATTLIST p
	id ID #IMPLIED
	n CDATA #IMPLIED
	loc CDATA #IMPLIED
	lang CDATA #IMPLIED
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT foreign 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | eg | bibl | biblFull | figure | cit | q | label 
	| list | listBibl | note | stage | table | text | anchor 
	| gap | index | interp | interpGrp | lb | milestone | pb | gaiji)* >
<!ATTLIST foreign 
	cert CDATA #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
	resp CDATA #IMPLIED
	TEIform CDATA "foreign" >

<!--  6.3.4:  Highlighted phrases (cont'd)                     -->
<!ELEMENT term (#PCDATA | gaiji | lb | pb | app | fan | l)*>
<!ATTLIST term
	rend CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!-- GLOSS is from the TEI set, but the attribute alt has been added (CW, 18.11.98) -->
<!ELEMENT gloss (#PCDATA | corr | gaiji | skgloss)*>
<!ATTLIST gloss
	n CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!-- SKGLOSS is added by CBETA -->
<!ELEMENT skgloss (gloss, term)>
<!ATTLIST skgloss
	n CDATA #IMPLIED
>
<!--  6.4.1:  Proper Nouns                                     -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!--  6.4.2:  Addresses and their components                   -->
<!ELEMENT address (addrLine)>
<!ELEMENT addrLine (#PCDATA)>
<!--  6.4.4:  Dates and times                                  -->
<!ELEMENT date (#PCDATA)>
<!--  6.5.1:  Editorial tags for correction                    -->
<!-- CORR is from the TEI set, but the attributes cf1, cf2 has been added (CW, 1.7.98) -->
<!ELEMENT corr (#PCDATA | gaiji | xref | anchor | lb | note | term)*>
<!ATTLIST corr
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	resp CDATA #IMPLIED
	cert CDATA #IMPLIED
	sic CDATA #IMPLIED
>
<!ELEMENT sic (#PCDATA | app | corr | gaiji | head | xref | anchor | l | lb | note | p | pb | sic | term)*>
<!ATTLIST sic
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	resp CDATA #IMPLIED
	cert CDATA #IMPLIED
	corr CDATA #IMPLIED
	n CDATA #IMPLIED
>

<!--  6.6:  Simple cross references                            -->
<!ELEMENT ref (#PCDATA | address | date | name | corr | gloss | term | title | ref | xref | anchor | bibl | list | note | figure | table | text)*>
<!ATTLIST ref
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	type CDATA #IMPLIED
	resp CDATA #IMPLIED
	crdate CDATA #IMPLIED
	targType CDATA #IMPLIED
	targOrder (Y | N | U) "U"
	evaluate (all | one | none) #IMPLIED
	target IDREFS #IMPLIED
	TEIform CDATA "ref"
>
<!--  6.7:  Lists and List Items                               -->
<!-- <!ELEMENT list (head?, (item | gaiji | lb | milestone | pb)*)> -->
<!ELEMENT list (#PCDATA | anchor | app | head | item | gaiji | lb | milestone | note | pb)*>
<!ATTLIST list
	id ID #IMPLIED
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT item (#PCDATA | anchor | byline | figure | gaiji | lb | list | app | pb | corr | note | p | ref | sic | title)*>
<!ATTLIST item
	id ID #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT head (#PCDATA | app | skgloss | corr | foreign | gaiji | lb | pb | note | anchor | title | l | sic | tt)*>
<!ATTLIST head
	rend CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!--  6.8.1:  Annotation                                       -->
<!ELEMENT note (#PCDATA | anchor | app | figure | p | corr | foreign | gaiji | note | skgloss | gloss | term | lb | list | pb | lg | l | fan | sic | tt | todo | xref)*>
<!ATTLIST note
	n CDATA #IMPLIED
	lang CDATA #IMPLIED
	resp CDATA #IMPLIED
	type CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!--  6.9.3:  Milestone tags  -->
<!ELEMENT pb EMPTY>
<!ATTLIST pb
	ed CDATA #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT milestone EMPTY>
<!ATTLIST milestone
	id ID #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	ed CDATA #IMPLIED
	n CDATA #IMPLIED
	unit CDATA #REQUIRED
	TEIform CDATA "milestone"
>
<!ELEMENT lb EMPTY>
<!ATTLIST lb
	id ID #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	ed CDATA #IMPLIED
	n CDATA #IMPLIED
	TEIform CDATA "lb"
>
<!--  6.10.1:  Tags for Bibliographic References               -->
<!ELEMENT bibl (#PCDATA)>
<!ATTLIST bibl
	lang CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | anchor | gaiji | app | foreign | note | lb | pb | sic | skgloss | corr | tt)*>
<!ATTLIST title
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!ELEMENT respStmt (resp | name)*>
<!ELEMENT resp (#PCDATA)>
<!--  6.10.2.2:  Tags for Bibliographic References (cont'd)    -->
<!ELEMENT author (#PCDATA | address | date | name | corr | gaiji | gloss | term | title | ref | xref | anchor)*>
<!ATTLIST author
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "author"
>
<!--  6.11.1:  Verse                                           -->
<!ELEMENT l (#PCDATA | gaiji | skgloss | corr | app | figure | foreign | note | lb | pb | sic | term | tt | anchor)*>
<!ATTLIST l
	rend CDATA #IMPLIED
>
<!ELEMENT lg (#PCDATA | gaiji | lb | l | pb | app | anchor | skgloss | gloss | term | head | p | note | sic | tt )*>
<!ATTLIST lg
	id ID #IMPLIED
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!--  7:  Top-level parts of default structure                 -->
<!ELEMENT text (body)>
<!ATTLIST text
	rend CDATA #IMPLIED
>
<!ELEMENT body (app | gaiji | lb | pb | head | juan | byline | div1 | milestone | mulu | note)*>

<!--  7.1.2:  Numbered divisions                               -->
<!ELEMENT div1 (#PCDATA | div2 | head | p | lg | juan | gaiji | lb | pb | byline | trailer | app | list | anchor | corr | mulu | xref | milestone | note | tt)*>
<!ATTLIST div1
	type CDATA #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT div2 (#PCDATA | div3 | anchor | app | byline | figure | gaiji | head | jhead | juan | lb | lg | list | milestone | mulu | note | p | pb | trailer | xref | tt)*>
<!ATTLIST div2
	type CDATA #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT div3 (#PCDATA | div4 | anchor | head | p | lg | milestone | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | qa | mulu | xref | tt)*>
<!ATTLIST div3
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div4 (#PCDATA | div5 | anchor | head | p | lg | milestone | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | qa | mulu | tt| xref)*>
<!ATTLIST div4
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div5 (#PCDATA | div6 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div5
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div6 (#PCDATA | div7 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div6
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div7 (#PCDATA | div8 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | milestone | mulu | tt)*>
<!ATTLIST div7
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div8 (#PCDATA | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div8
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!--  7.2.4:  Tags for start and end of divisions              -->
<!ELEMENT trailer (#PCDATA | anchor | gaiji | lb | corr | app | title | pb | note | head)*>
<!ELEMENT byline (#PCDATA | app | gaiji | lb | pb | corr | foreign | note | anchor | sic | tt)*>
<!ATTLIST byline
	type CDATA #IMPLIED
>
<!--  14.2.1:  Extended pointers                               -->
<!-- XREF is from the TEI set, but the attributes loc, rend has been added (Chou, Ray, 2000/9/5 10:18AM) -->
<!ELEMENT xref (#PCDATA | anchor | app | lb | note)*>
<!ATTLIST xref
	doc CDATA #IMPLIED
	loc CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!--  14.3:  Segments and Anchors                              -->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
	id ID #IMPLIED
	n CDATA #IMPLIED
>
<!--  22:  Tables, Formulae, Figures                           -->
<!--  22.1.1:  Tables                                          -->
<!ELEMENT table ((head)*, (row)+)>
<!ATTLIST table
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	TEIform CDATA "table"
>
<!ELEMENT row ((cell | table)+)>
<!ATTLIST row
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	role CDATA "data"
	TEIform CDATA "row"
>
<!ELEMENT cell (#PCDATA | app | address | date | name | corr | gloss | term | title | ref | xref | anchor | bibl | list | note | figure | sic | table | text | pb | lb | gaiji)*>
<!ATTLIST cell
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	role CDATA "data"
	rows CDATA "1"
	cols CDATA "1"
	TEIform CDATA "cell"
>
<!--  22.3:  Figures  -->
<!ELEMENT figure EMPTY>
<!ATTLIST figure
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	entity ENTITY #IMPLIED
	TEIform CDATA "figure"
>
<!ELEMENT app (lem?, rdg+)>
<!-- type, source attributes are added by Ray -->
<!ATTLIST app
	type CDATA #IMPLIED
	source CDATA #IMPLIED
	wit CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	yuan CDATA #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	word-count CDATA #IMPLIED
	TEIform CDATA "app"
>
<!ELEMENT lem (#PCDATA | anchor | app | div1 | div2 | figure | gaiji | item | lb | milestone | byline | note | l | pb | skgloss | lg | fan | foreign | head | p | juan | title | list | corr | mulu | sic | term | tt | xref )*>
<!ATTLIST lem
	wit CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	resp CDATA #IMPLIED
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	TEIform CDATA "lem"
>

<!ELEMENT rdg (#PCDATA | figure | gaiji | lb | note | fan | p | todo)*>
<!-- resp attribute is added by CBETA -->
<!ATTLIST rdg
	type CDATA #IMPLIED
	cf1 CDATA #IMPLIED
	wit CDATA #IMPLIED
	resp CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "rdg"
>
<!ELEMENT span (#PCDATA | gaiji | lb | app | pb)*>
<!ATTLIST span
	id ID #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!-- CBETA specific elements -->
<!ELEMENT witList (witness)+>
<!ELEMENT witness (#PCDATA | note)*>
<!ATTLIST witness
	sigil CDATA #IMPLIED
	included CDATA #IMPLIED
>
<!ELEMENT jhead (#PCDATA | app | corr | foreign | gaiji | lb | pb | note | anchor | sic | skgloss | title | tt)*>
<!ATTLIST jhead
	type CDATA #IMPLIED
>
<!ELEMENT juan (#PCDATA | anchor | skgloss | app | corr | gaiji | lb | pb | note | jhead | head | byline | title | mulu)*>
<!ATTLIST juan
	fun CDATA #IMPLIED
	n CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT fan (#PCDATA | anchor | zi | yin)*>
<!ELEMENT zi (#PCDATA | anchor | app | lb | note | gaiji | sic | yin)*>
<!ELEMENT sg (#PCDATA | anchor | app | note | gaiji | corr | lb | sic)*>
<!ATTLIST sg
	type CDATA #IMPLIED
>
<!ELEMENT yin (#PCDATA | anchor | app | lb | note | gaiji | zi | sg)*>
<!ATTLIST yin
	yuan CDATA #IMPLIED
>
<!ELEMENT gaiji (#PCDATA)>
<!ATTLIST gaiji
	id ID #IMPLIED
	mojikyo CDATA #IMPLIED
	mofont CDATA #IMPLIED
	mochar CDATA #IMPLIED
	cb CDATA #IMPLIED
	des CDATA #IMPLIED
	uni CDATA #IMPLIED
	nor CDATA #IMPLIED
	sdchar CDATA #IMPLIED
	big5 CDATA #IMPLIED
	cbdia CDATA #IMPLIED
	udia CDATA #IMPLIED
	cx CDATA #IMPLIED
>
<!ELEMENT mulu (#PCDATA)>
<!ATTLIST mulu
	id ID #IMPLIED
	type CDATA #IMPLIED
	level CDATA #IMPLIED
	n CDATA #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT tt (#PCDATA | anchor | t | lb)*>
<!ATTLIST tt
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	n CDATA #IMPLIED
	word-count CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT t (#PCDATA | corr | foreign | gaiji | yin | app | note | lb | l | lg | anchor | pb | sic | title)*>
<!ATTLIST t
	lang CDATA #IMPLIED
	place CDATA #IMPLIED
	repeat CDATA #IMPLIED
	resp CDATA #IMPLIED
	rend CDATA #IMPLIED
	cert CDATA #IMPLIED
>

<!ELEMENT todo EMPTY>
<!ATTLIST todo
	type CDATA #IMPLIED
>

<!ELEMENT qa (answer | lb | question)*>
<!ELEMENT question (#PCDATA|lb|p)*>
<!ELEMENT answer (#PCDATA|lb|p)*>

<!-- Notations -->
<!NOTATION doc SYSTEM "uedit32.exe">
<!NOTATION GIF SYSTEM "acdsee32.exe">

=== heavenchou/xml_p4/T01/T01n0084.xml
<?xml version="1.0" encoding="big5" ?><!-- -*- coding: big5-dos -*- -->
<?xml-stylesheet type="text/xsl" href="../dtd/cbeta.xsl" ?>
<!DOCTYPE TEI.2 SYSTEM "../dtd/cbetaxml.dtd"
[<!ENTITY % ENTY SYSTEM "T01n0084.ent">
<!ENTITY % CBENT SYSTEM "../dtd/cbeta.ent">
%ENTY;
%CBENT;
]>
<TEI.2>
<teiHeader>
	<fileDesc>
		<titleStmt>
			<title>Taisho Tripitaka, Electronic version, No. 0084 分別布施經</title>
			<author>宋 施護譯</author>
			<respStmt>
				<resp>Electronic Version by</resp>
				<name>CBETA</name>
			</respStmt>
		</titleStmt>
	<editionStmt>
		<edition>$Revision: 1.6 $ (Big5)<date>$Date: 2006/04/12 15:27:12 $</date></edition>
	</editionStmt>
	<extent>1卷</extent>
	<publicationStmt>
		<distributor>
			<name>中華電子佛典協會 (CBETA)</name>
			<address>
				<addrLine>service@cbeta.org</addrLine>
			</address>
		</distributor>
		<availability>
			<p>Available for non-commercial use when distributed with this header intact.</p>
		</availability>
		<date>$Date: 2006/04/12 15:27:12 $</date>
	</publicationStmt>
	<sourceDesc>
		<bibl>Taisho Tripitaka Vol. 1, No. 084 &desc;</bibl>
	</sourceDesc>
</fileDesc>
<encodingDesc>
	<projectDesc>
		<p lang="eng" type="ly">Text as provided by Mr. Hsiao Chen-Kuo, Text as provided by Mr. Chang Wen-Ming, Text as provided by Anonymous, USA</p>
		<p lang="chi" type="ly">蕭鎮國大德提供，張文明大德提供，北美某大德提供</p>
	</projectDesc>
</encodingDesc>
<profileDesc>
		<langUsage>
			<language id="eng">English</language>
			<language id="chi">Chinese</language>
		</langUsage>
	</profileDesc>
	<revisionDesc>
	<change>
		<date>19990810/22:32:32</date>
		<respStmt><name>CW</name><resp>ed.</resp></respStmt>
		<item>Created initial TEI XML version with BASICX.BAT (99/8/10)</item>
	</change>
<!--
$Log: T01n0084.xml,v $
Revision 1.6  2006/04/12 15:27:12  saywhat
lem 加 wit 屬性，p, lg, item 第二次加 id 屬性

Revision 1.4  2004/10/07 04:49:35  saywhat
執行圈點程式

Revision 1.3  2004/04/20 08:36:49  maha
「版本日期」標記修訂

Revision 1.2  2003/06/23 05:31:46  saywhat
[＊]校勘插入XML

Revision 1.1.1.1  2003/05/05 04:08:21  ray
recover cvs

Revision 1.16  2002/11/27 11:14:02  saywhat
校勘插入處理

Revision 1.15  2002/11/04 10:30:57  ray
tei.2 => TEI.2

Revision 1.14  2002/10/07 13:04:40  moved
modified

Revision 1.13  2002/07/29 09:43:01  vinking
modified lang

Revision 1.12  2002/04/03 03:37:27  ray
xml:stylesheet => xml-stylesheet

Revision 1.11  2001/07/24 06:47:15  ray
add 作者、譯者 <author> 卷數 <extent>

Revision 1.10  2001/05/25 08:41:17  ray
經號統一為四碼

Revision 1.9  2001/04/01 05:53:53  ray
heaven 重新加入 <milestone>

Revision 1.8  2001/03/30 00:35:24  ray
缺字CB碼由四碼增長為五碼

Revision 1.7  2001/02/07 06:39:39  chris
Fixed problem with comment in the previous checkin

Revision 1.6  2001/02/03 07:28:22  chris
Added keywords $Revision: 1.6 $, $Date: 2006/04/12 15:27:12 $ and $Log.
Added comment  for Emacs

-->
 </revisionDesc>
</teiHeader>
<text><body>
<lb n="0903b20" ed="T"/>
<milestone n="1" unit="juan"/>
<lb n="0903b21" ed="T"/>
<lb n="0903b22" ed="T"/><head type="no">No. 84 [No. 26(180)]</head><div1 type="jing">
<lb n="0903b23" ed="T"/><juan n="001" fun="open"><mulu n="001" type="卷"/><jhead>佛說分別布施經</jhead></juan>
<lb n="0903b24" ed="T"/>
<lb n="0903b25" ed="T"/><byline type="Translator"><note n="0903005" resp="Taisho" place="foot text" type="orig">（宋）＋西【明】</note><app n="0903005"><lem wit="【大】">西</lem><rdg resp="Taisho" wit="【明】">宋西</rdg></app>天<note n="0903006" resp="Taisho" place="foot text" type="orig">〔譯經〕－【明】</note><app n="0903006"><lem wit="【大】">譯經</lem><rdg resp="Taisho" wit="【明】">&lac;</rdg></app>三藏朝奉大夫試鴻臚
<lb n="0903b26" ed="T"/>卿傳法大師<note n="0903007" resp="Taisho" place="foot text" type="orig">〔臣〕－【明】</note><app n="0903007"><lem wit="【大】">臣</lem><rdg resp="Taisho" wit="【明】">&lac;</rdg></app>施護奉　詔譯</byline>
<lb n="0903b27" ed="T"/><p id="pT01p0903b2701">如是我聞。一時佛在釋種住處迦毗羅城尼
<lb n="0903b28" ed="T"/>拘陀樹園。與苾芻眾俱。爾時有一苾芻尼名
<lb n="0903b29" ed="T"/>摩訶波闍波提。持新&CB00626;衣來詣佛所。到佛所
<pb n="0903c" id="T01.0084.0903c" ed="T"/>
<lb n="0903c01" ed="T"/>已頂禮佛足退住一面。即白佛言。世尊。此新
<lb n="0903c02" ed="T"/>&CB00626;衣我自手作奉上世尊。惟願納受。令我長
<lb n="0903c03" ed="T"/>夜得大利樂。</p>
<lb n="0903c04" ed="T"/><p id="pT01p0903c0401">爾時佛告摩訶波闍波提。汝可持此&CB00626;衣施
<lb n="0903c05" ed="T"/>諸大眾。所獲勝利同供養我等無有異。是時
<lb n="0903c06" ed="T"/>摩訶波闍波提苾芻尼。重白佛言。我本發心。
<lb n="0903c07" ed="T"/>唯為世尊故造此衣。願佛納受。令我長夜得
<lb n="0903c08" ed="T"/>大利樂。如是三復慇懃勸請。佛亦如是三復
<lb n="0903c09" ed="T"/>答言。但當平等施諸大眾。所獲勝利與我無
<lb n="0903c10" ed="T"/>異。是時尊者阿難。侍於佛側見是事已。前白
<lb n="0903c11" ed="T"/>佛言。世尊。此摩訶波闍波提苾芻尼。是佛之
<lb n="0903c12" ed="T"/>親有大恩德。唯佛自知。此所奉衣佛為納受。
<lb n="0903c13" ed="T"/>今正是時。令摩訶波闍波提於長夜中得大
<lb n="0903c14" ed="T"/>利樂。佛言阿難。如是如是。此摩訶波闍波提
<lb n="0903c15" ed="T"/>是吾之親有大恩德。我亦自知。今自手造衣
<lb n="0903c16" ed="T"/>來施於我。甚為難事。何以故。阿難當知。所有
<lb n="0903c17" ed="T"/>補特伽羅能起淨信心。歸依佛法僧者甚為
<lb n="0903c18" ed="T"/>難事。又復能持不殺不盜不婬不妄不飲酒
<lb n="0903c19" ed="T"/>等近事戒法。如是補特伽羅轉復難作。何況
<lb n="0903c20" ed="T"/>於佛世尊。合掌恭敬而行布施。施已淨信於
<lb n="0903c21" ed="T"/>佛無疑。及法僧伽亦無疑惑。乃至苦集滅道
<lb n="0903c22" ed="T"/>四聖諦理。永斷疑見。阿難。今此摩訶波闍波
<lb n="0903c23" ed="T"/>提苾芻尼。能起淨信心歸依佛法僧。受持不
<lb n="0903c24" ed="T"/>殺不盜不婬不妄不飲酒等近事戒法。而能
<lb n="0903c25" ed="T"/>於佛及法僧伽。乃至苦集滅道四聖諦理。已
<lb n="0903c26" ed="T"/>斷疑惑。此苾芻尼難作能作。佛亦自知。</p>
<lb n="0903c27" ed="T"/><p id="pT01p0903c2701">阿難有十四種較量布施。何等十四。一者於
<lb n="0903c28" ed="T"/>病苦人而行布施。二者於破戒人而行布施。
<lb n="0903c29" ed="T"/>三者於持戒人而行布施。四者於離染人而
<pb n="0904a" id="T01.0084.0904a" ed="T"/>
<lb n="0904a01" ed="T"/>行布施。五者於須陀洹向而行布施。六者於
<lb n="0904a02" ed="T"/>須陀洹果而行布施。七者於斯陀含向而行
<lb n="0904a03" ed="T"/>布施。八者於斯陀含果而行布施。九者於阿
<lb n="0904a04" ed="T"/>那<note n="0904001" resp="Taisho" place="foot text" type="orig">含＝舍【明】＊</note><app n="0904001"><lem wit="【大】">含</lem><rdg resp="Taisho" wit="【明】">舍</rdg></app>向而行布施。十者於阿那<app source="0904001" type="＊"><lem wit="【大】">含</lem><rdg resp="Taisho" wit="【明】">舍</rdg></app>果而行
<lb n="0904a05" ed="T"/>布施。十一者於阿羅漢向而行布施。十二者
<lb n="0904a06" ed="T"/>於阿羅漢果而行布施。十三者於諸緣覺而
<lb n="0904a07" ed="T"/>行布施。十四者於如來應供正等正覺而行
<lb n="0904a08" ed="T"/>布施。阿難。汝今當知施病苦人獲二倍福。施
<lb n="0904a09" ed="T"/>破戒人獲百倍福。施持戒人獲千倍福。施離
<lb n="0904a10" ed="T"/>染人獲百千倍福。施須陀洹向獲無量福。何
<lb n="0904a11" ed="T"/>況須陀洹果。施斯陀<app source="0904001" type="＊"><lem wit="【大】">含</lem><rdg resp="Taisho" wit="【明】">舍</rdg></app>向獲無量福。何況斯
<lb n="0904a12" ed="T"/>陀<app source="0904001" type="＊"><lem wit="【大】">含</lem><rdg resp="Taisho" wit="【明】">舍</rdg></app>果。施阿那含向獲無量福。何況阿
<lb n="0904a13" ed="T"/>那<app source="0904001" type="＊"><lem wit="【大】">含</lem><rdg resp="Taisho" wit="【明】">舍</rdg></app>果。施阿羅漢向獲無量福。何況阿羅
<lb n="0904a14" ed="T"/>漢果。施諸緣覺獲無量福。何況如來應供正
<lb n="0904a15" ed="T"/>等正覺。如是名為較量十四種布施功德。復
<lb n="0904a16" ed="T"/>次阿難。當知布施大眾有其七種。一者施佛
<lb n="0904a17" ed="T"/>現前諸苾芻眾。二者施佛滅後諸苾芻眾。三
<lb n="0904a18" ed="T"/>者施佛滅後苾芻尼眾。四者施佛滅後苾芻
<lb n="0904a19" ed="T"/>苾芻尼二眾。五者施佛滅後遊方行化諸苾
<lb n="0904a20" ed="T"/>芻眾。六者施佛滅後遊方行化苾芻尼眾。七
<lb n="0904a21" ed="T"/>者施佛滅後遊方行化苾芻苾芻尼二眾。如
<lb n="0904a22" ed="T"/>是名為七種大眾。當行布施。</p>
<lb n="0904a23" ed="T"/><p id="pT01p0904a2301">復次阿難。當知有四種布施清淨。何等為四。
<lb n="0904a24" ed="T"/>一者能施清淨即無受者。二者所施清淨即
<lb n="0904a25" ed="T"/>無受者。三者能受清淨即無施者。四者所受
<lb n="0904a26" ed="T"/>清淨即無施者。阿難。何名能施清淨即無受
<lb n="0904a27" ed="T"/>者。謂由施者不取其相。即身業清淨口業清
<lb n="0904a28" ed="T"/>淨意業清淨。正命清淨見亦清淨。如是具足
<lb n="0904a29" ed="T"/>即無施相。以無施故即無受者。若施者有所
<pb n="0904b" id="T01.0084.0904b" ed="T"/>
<lb n="0904b01" ed="T"/>見相。即身口意三業不清淨。命亦不清淨見
<lb n="0904b02" ed="T"/>亦不清淨。若離是相即施者受者二皆清淨。</p>
<lb n="0904b03" ed="T"/><p id="pT01p0904b0301">又復何名所施清淨即無受者。若受者身業
<lb n="0904b04" ed="T"/>不清淨口業不清淨意業不清淨。命不清淨
<lb n="0904b05" ed="T"/>見不清淨。即有所施相。若受者三業清淨。命
<lb n="0904b06" ed="T"/>清淨見清淨。如是具足即無所施相。由離相
<lb n="0904b07" ed="T"/>故即所施清淨。</p>
<lb n="0904b08" ed="T"/><p id="pT01p0904b0801">又復何名能受清淨即無施者。若受者身口
<lb n="0904b09" ed="T"/>意三業不清淨。命不清淨見不清淨。即有能
<lb n="0904b10" ed="T"/>受相。若離是相即無施者。</p>
<lb n="0904b11" ed="T"/><p id="pT01p0904b1101">又復何名所受清淨即無施者。謂由施者三
<lb n="0904b12" ed="T"/>業清淨。命清淨見清淨。即無所施。由離施故
<lb n="0904b13" ed="T"/>即無所受。是故所受清淨阿難若能如是了
<lb n="0904b14" ed="T"/>知。即得四種布施清淨。</p>
<lb n="0904b15" ed="T"/><p id="pT01p0904b1501">爾時摩訶波闍波提苾芻尼。聞佛宣說種種
<lb n="0904b16" ed="T"/>布施法已。即持是衣施諸大眾是時諸苾芻
<lb n="0904b17" ed="T"/>眾即為納受。</p>
<lb n="0904b18" ed="T"/><p id="pT01p0904b1801">佛告阿難。於當來世若有信心善男子等。能
<lb n="0904b19" ed="T"/>於大眾起淨信心。而行布施者。當知是人獲
<lb n="0904b20" ed="T"/>福無量。何況於今現在行施。</p>
<lb n="0904b21" ed="T"/><p id="pT01p0904b2101">爾時尊者阿難及摩訶波闍波提苾芻尼聞佛
<lb n="0904b22" ed="T"/>說已。歡喜踊躍信受奉行。</p>
<lb n="0904b23" ed="T"/><juan n="001" fun="close"><jhead>佛說分別布施經</jhead></juan>
</div1></body></text></TEI.2>
