=== heavenchou/xml_p4/dtd/cbetaxml.dtd
<!-- CBETA project DTD, generated with FRED 31.12.98  (CW)

converted to XML form 2.1.99 (CW)

-->
<!--  A TEI document is a text preceded by a TEI header.       -->
<!ELEMENT TEI.2 (teiHeader, text)>
<!ELEMENT teiHeader 
	(fileDesc, encodingDesc*, profileDesc*, revisionDesc?) >
<!ELEMENT fileDesc (titleStmt, (editionStmt)?, (extent)?, publicationStmt, (sourceDesc)+)>
<!ELEMENT titleStmt (((title)+, (author | respStmt)*))>
<!ELEMENT editionStmt (edition)>
<!ELEMENT edition (#PCDATA | date)*>
<!ELEMENT extent (#PCDATA | address | date | name | corr | gloss | term | title | ref | xref | anchor)*>
<!ATTLIST extent
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "extent"
>
<!--  5.2.4:  The publication statement                        -->
<!ELEMENT publicationStmt (distributor, availability, date)>
<!ELEMENT distributor (name+, address)>
<!ELEMENT availability (p)>
<!--  5.2.7:  The source description                           -->
<!ELEMENT sourceDesc (bibl+, p?)>
<!--  5.3:  The encoding description                           -->
<!ELEMENT encodingDesc (projectDesc, witList?)>
<!--  5.3.1:  The project description                          -->
<!ELEMENT projectDesc (p+)>
<!--  5.4 The Profile Description -->
<!ELEMENT profileDesc 
	(creation?, langUsage*, textClass*) >
<!ATTLIST profileDesc 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "profileDesc" >
<!ELEMENT creation 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST creation 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "creation" >

<!ELEMENT langUsage 
	(p | language)+ >
<!ATTLIST langUsage 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	default (YES | NO) "NO"
	TEIform CDATA "langUsage" >

<!ELEMENT language 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST language 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	wsd ENTITY #IMPLIED
	usage CDATA #IMPLIED
	TEIform CDATA "language" >

<!ELEMENT textClass 
	(classCode | catRef | keywords)* >
<!ATTLIST textClass 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	default (YES | NO) "NO"
	TEIform CDATA "textClass" >

<!ELEMENT keywords 
	(term+ | list) >
<!ATTLIST keywords 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	scheme IDREF #IMPLIED
	TEIform CDATA "keywords" >

<!ELEMENT classCode 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | anchor | gap | index | interp | interpGrp | 
	lb | milestone | pb)* >
<!ATTLIST classCode 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	scheme IDREF #IMPLIED
	TEIform CDATA "classCode" >

<!ELEMENT catRef 
	EMPTY >
<!ATTLIST catRef 
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	target IDREFS #REQUIRED
	scheme IDREF #IMPLIED
	TEIform CDATA "catRef" >
	
<!--  5.5:  The Revision Description                           -->
<!ELEMENT revisionDesc (change)+>
<!ELEMENT change (date, respStmt, item)>
<!--  6.1:  Paragraph                                          -->
<!ELEMENT p (#PCDATA | anchor | app | corr | fan | figure | foreign | gaiji | l | lb | note | pb | sic | skgloss | span | table | term | tt)*>
<!ATTLIST p
	id ID #IMPLIED
	n CDATA #IMPLIED
	loc CDATA #IMPLIED
	lang CDATA #IMPLIED
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT foreign 
	(#PCDATA | ident | code | kw | abbr | address | date | name 
	| num | rs | time | add | corr | del | orig | reg | sic 
	| unclear | formula | emph | foreign | gloss | hi | mentioned 
	| soCalled | term | title | ptr | ref | xptr | xref | s 
	| seg | gi | eg | bibl | biblFull | figure | cit | q | label 
	| list | listBibl | note | stage | table | text | anchor 
	| gap | index | interp | interpGrp | lb | milestone | pb | gaiji)* >
<!ATTLIST foreign 
	cert CDATA #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	ana IDREFS #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
	resp CDATA #IMPLIED
	TEIform CDATA "foreign" >

<!--  6.3.4:  Highlighted phrases (cont'd)                     -->
<!ELEMENT term (#PCDATA | gaiji | lb | pb | app | fan | l)*>
<!ATTLIST term
	rend CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!-- GLOSS is from the TEI set, but the attribute alt has been added (CW, 18.11.98) -->
<!ELEMENT gloss (#PCDATA | corr | gaiji | skgloss)*>
<!ATTLIST gloss
	n CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!-- SKGLOSS is added by CBETA -->
<!ELEMENT skgloss (gloss, term)>
<!ATTLIST skgloss
	n CDATA #IMPLIED
>
<!--  6.4.1:  Proper Nouns                                     -->
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!--  6.4.2:  Addresses and their components                   -->
<!ELEMENT address (addrLine)>
<!ELEMENT addrLine (#PCDATA)>
<!--  6.4.4:  Dates and times                                  -->
<!ELEMENT date (#PCDATA)>
<!--  6.5.1:  Editorial tags for correction                    -->
<!-- CORR is from the TEI set, but the attributes cf1, cf2 has been added (CW, 1.7.98) -->
<!ELEMENT corr (#PCDATA | gaiji | xref | anchor | lb | note | term)*>
<!ATTLIST corr
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	resp CDATA #IMPLIED
	cert CDATA #IMPLIED
	sic CDATA #IMPLIED
>
<!ELEMENT sic (#PCDATA | app | corr | gaiji | head | xref | anchor | l | lb | note | p | pb | sic | term)*>
<!ATTLIST sic
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	resp CDATA #IMPLIED
	cert CDATA #IMPLIED
	corr CDATA #IMPLIED
	n CDATA #IMPLIED
>

<!--  6.6:  Simple cross references                            -->
<!ELEMENT ref (#PCDATA | address | date | name | corr | gloss | term | title | ref | xref | anchor | bibl | list | note | figure | table | text)*>
<!ATTLIST ref
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	type CDATA #IMPLIED
	resp CDATA #IMPLIED
	crdate CDATA #IMPLIED
	targType CDATA #IMPLIED
	targOrder (Y | N | U) "U"
	evaluate (all | one | none) #IMPLIED
	target IDREFS #IMPLIED
	TEIform CDATA "ref"
>
<!--  6.7:  Lists and List Items                               -->
<!-- <!ELEMENT list (head?, (item | gaiji | lb | milestone | pb)*)> -->
<!ELEMENT list (#PCDATA | anchor | app | head | item | gaiji | lb | milestone | note | pb)*>
<!ATTLIST list
	id ID #IMPLIED
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT item (#PCDATA | anchor | byline | figure | gaiji | lb | list | app | pb | corr | note | p | ref | sic | title)*>
<!ATTLIST item
	id ID #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT head (#PCDATA | app | skgloss | corr | foreign | gaiji | lb | pb | note | anchor | title | l | sic | tt)*>
<!ATTLIST head
	rend CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!--  6.8.1:  Annotation                                       -->
<!ELEMENT note (#PCDATA | anchor | app | figure | p | corr | foreign | gaiji | note | skgloss | gloss | term | lb | list | pb | lg | l | fan | sic | tt | todo | xref)*>
<!ATTLIST note
	n CDATA #IMPLIED
	lang CDATA #IMPLIED
	resp CDATA #IMPLIED
	type CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!--  6.9.3:  Milestone tags  -->
<!ELEMENT pb EMPTY>
<!ATTLIST pb
	ed CDATA #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT milestone EMPTY>
<!ATTLIST milestone
	id ID #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	ed CDATA #IMPLIED
	n CDATA #IMPLIED
	unit CDATA #REQUIRED
	TEIform CDATA "milestone"
>
<!ELEMENT lb EMPTY>
<!ATTLIST lb
	id ID #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	ed CDATA #IMPLIED
	n CDATA #IMPLIED
	TEIform CDATA "lb"
>
<!--  6.10.1:  Tags for Bibliographic References               -->
<!ELEMENT bibl (#PCDATA)>
<!ATTLIST bibl
	lang CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | anchor | gaiji | app | foreign | note | lb | pb | sic | skgloss | corr | tt)*>
<!ATTLIST title
	type CDATA #IMPLIED
	lang CDATA #IMPLIED
>
<!ELEMENT respStmt (resp | name)*>
<!ELEMENT resp (#PCDATA)>
<!--  6.10.2.2:  Tags for Bibliographic References (cont'd)    -->
<!ELEMENT author (#PCDATA | address | date | name | corr | gaiji | gloss | term | title | ref | xref | anchor)*>
<!ATTLIST author
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "author"
>
<!--  6.11.1:  Verse                                           -->
<!ELEMENT l (#PCDATA | gaiji | skgloss | corr | app | figure | foreign | note | lb | pb | sic | term | tt | anchor)*>
<!ATTLIST l
	rend CDATA #IMPLIED
>
<!ELEMENT lg (#PCDATA | gaiji | lb | l | pb | app | anchor | skgloss | gloss | term | head | p | note | sic | tt )*>
<!ATTLIST lg
	id ID #IMPLIED
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!--  7:  Top-level parts of default structure                 -->
<!ELEMENT text (body)>
<!ATTLIST text
	rend CDATA #IMPLIED
>
<!ELEMENT body (app | gaiji | lb | pb | head | juan | byline | div1 | milestone | mulu | note)*>

<!--  7.1.2:  Numbered divisions                               -->
<!ELEMENT div1 (#PCDATA | div2 | head | p | lg | juan | gaiji | lb | pb | byline | trailer | app | list | anchor | corr | mulu | xref | milestone | note | tt)*>
<!ATTLIST div1
	type CDATA #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT div2 (#PCDATA | div3 | anchor | app | byline | figure | gaiji | head | jhead | juan | lb | lg | list | milestone | mulu | note | p | pb | trailer | xref | tt)*>
<!ATTLIST div2
	type CDATA #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!ELEMENT div3 (#PCDATA | div4 | anchor | head | p | lg | milestone | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | qa | mulu | xref | tt)*>
<!ATTLIST div3
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div4 (#PCDATA | div5 | anchor | head | p | lg | milestone | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | qa | mulu | tt| xref)*>
<!ATTLIST div4
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div5 (#PCDATA | div6 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div5
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div6 (#PCDATA | div7 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div6
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div7 (#PCDATA | div8 | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | milestone | mulu | tt)*>
<!ATTLIST div7
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!ELEMENT div8 (#PCDATA | anchor | head | p | lg | juan | jhead | gaiji | lb | list | note | pb | byline | trailer | app | mulu | milestone | tt)*>
<!ATTLIST div8
	type CDATA #IMPLIED
	n CDATA #IMPLIED
>
<!--  7.2.4:  Tags for start and end of divisions              -->
<!ELEMENT trailer (#PCDATA | anchor | gaiji | lb | corr | app | title | pb | note | head)*>
<!ELEMENT byline (#PCDATA | app | gaiji | lb | pb | corr | foreign | note | anchor | sic | tt)*>
<!ATTLIST byline
	type CDATA #IMPLIED
>
<!--  14.2.1:  Extended pointers                               -->
<!-- XREF is from the TEI set, but the attributes loc, rend has been added (Chou, Ray, 2000/9/5 10:18AM) -->
<!ELEMENT xref (#PCDATA | anchor | app | lb | note)*>
<!ATTLIST xref
	doc CDATA #IMPLIED
	loc CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!--  14.3:  Segments and Anchors                              -->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
	id ID #IMPLIED
	n CDATA #IMPLIED
>
<!--  22:  Tables, Formulae, Figures                           -->
<!--  22.1.1:  Tables                                          -->
<!ELEMENT table ((head)*, (row)+)>
<!ATTLIST table
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	TEIform CDATA "table"
>
<!ELEMENT row ((cell | table)+)>
<!ATTLIST row
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	role CDATA "data"
	TEIform CDATA "row"
>
<!ELEMENT cell (#PCDATA | app | address | date | name | corr | gloss | term | title | ref | xref | anchor | bibl | list | note | figure | sic | table | text | pb | lb | gaiji)*>
<!ATTLIST cell
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	role CDATA "data"
	rows CDATA "1"
	cols CDATA "1"
	TEIform CDATA "cell"
>
<!--  22.3:  Figures  -->
<!ELEMENT figure EMPTY>
<!ATTLIST figure
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	entity ENTITY #IMPLIED
	TEIform CDATA "figure"
>
<!ELEMENT app (lem?, rdg+)>
<!-- type, source attributes are added by Ray -->
<!ATTLIST app
	type CDATA #IMPLIED
	source CDATA #IMPLIED
	wit CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	yuan CDATA #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	word-count CDATA #IMPLIED
	TEIform CDATA "app"
>
<!ELEMENT lem (#PCDATA | anchor | app | div1 | div2 | figure | gaiji | item | lb | milestone | byline | note | l | pb | skgloss | lg | fan | foreign | head | p | juan | title | list | corr | mulu | sic | term | tt | xref )*>
<!ATTLIST lem
	wit CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	resp CDATA #IMPLIED
	cf1 CDATA #IMPLIED
	cf2 CDATA #IMPLIED
	TEIform CDATA "lem"
>

<!ELEMENT rdg (#PCDATA | figure | gaiji | lb | note | fan | p | todo)*>
<!-- resp attribute is added by CBETA -->
<!ATTLIST rdg
	type CDATA #IMPLIED
	cf1 CDATA #IMPLIED
	wit CDATA #IMPLIED
	resp CDATA #IMPLIED
	ana IDREFS #IMPLIED
	corresp IDREFS #IMPLIED
	from IDREF #IMPLIED
	to IDREF #IMPLIED
	next IDREF #IMPLIED
	prev IDREF #IMPLIED
	id ID #IMPLIED
	n CDATA #IMPLIED
	lang IDREF #IMPLIED
	rend CDATA #IMPLIED
	TEIform CDATA "rdg"
>
<!ELEMENT span (#PCDATA | gaiji | lb | app | pb)*>
<!ATTLIST span
	id ID #IMPLIED
	n CDATA #IMPLIED
	rend CDATA #IMPLIED
>
<!-- CBETA specific elements -->
<!ELEMENT witList (witness)+>
<!ELEMENT witness (#PCDATA | note)*>
<!ATTLIST witness
	sigil CDATA #IMPLIED
	included CDATA #IMPLIED
>
<!ELEMENT jhead (#PCDATA | app | corr | foreign | gaiji | lb | pb | note | anchor | sic | skgloss | title | tt)*>
<!ATTLIST jhead
	type CDATA #IMPLIED
>
<!ELEMENT juan (#PCDATA | anchor | skgloss | app | corr | gaiji | lb | pb | note | jhead | head | byline | title | mulu)*>
<!ATTLIST juan
	fun CDATA #IMPLIED
	n CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT fan (#PCDATA | anchor | zi | yin)*>
<!ELEMENT zi (#PCDATA | anchor | app | lb | note | gaiji | sic | yin)*>
<!ELEMENT sg (#PCDATA | anchor | app | note | gaiji | corr | lb | sic)*>
<!ATTLIST sg
	type CDATA #IMPLIED
>
<!ELEMENT yin (#PCDATA | anchor | app | lb | note | gaiji | zi | sg)*>
<!ATTLIST yin
	yuan CDATA #IMPLIED
>
<!ELEMENT gaiji (#PCDATA)>
<!ATTLIST gaiji
	id ID #IMPLIED
	mojikyo CDATA #IMPLIED
	mofont CDATA #IMPLIED
	mochar CDATA #IMPLIED
	cb CDATA #IMPLIED
	des CDATA #IMPLIED
	uni CDATA #IMPLIED
	nor CDATA #IMPLIED
	sdchar CDATA #IMPLIED
	big5 CDATA #IMPLIED
	cbdia CDATA #IMPLIED
	udia CDATA #IMPLIED
	cx CDATA #IMPLIED
>
<!ELEMENT mulu (#PCDATA)>
<!ATTLIST mulu
	id ID #IMPLIED
	type CDATA #IMPLIED
	level CDATA #IMPLIED
	n CDATA #IMPLIED
	label CDATA #IMPLIED
>
<!ELEMENT tt (#PCDATA | anchor | t | lb)*>
<!ATTLIST tt
	type CDATA #IMPLIED
	rend CDATA #IMPLIED
	n CDATA #IMPLIED
	word-count CDATA #IMPLIED
	place CDATA #IMPLIED
>
<!ELEMENT t (#PCDATA | corr | foreign | gaiji | yin | app | note | lb | l | lg | anchor | pb | sic | title)*>
<!ATTLIST t
	lang CDATA #IMPLIED
	place CDATA #IMPLIED
	repeat CDATA #IMPLIED
	resp CDATA #IMPLIED
	rend CDATA #IMPLIED
	cert CDATA #IMPLIED
>

<!ELEMENT todo EMPTY>
<!ATTLIST todo
	type CDATA #IMPLIED
>

<!ELEMENT qa (answer | lb | question)*>
<!ELEMENT question (#PCDATA|lb|p)*>
<!ELEMENT answer (#PCDATA|lb|p)*>

<!-- Notations -->
<!NOTATION doc SYSTEM "uedit32.exe">
<!NOTATION GIF SYSTEM "acdsee32.exe">

=== heavenchou/xml_p4/T15/T15n0605.xml
<?xml version="1.0" encoding="cp950" ?>
<?xml-stylesheet type="text/xsl" href="../dtd/cbeta.xsl" ?>
<!DOCTYPE TEI.2 SYSTEM "../dtd/cbetaxml.dtd"
[<!ENTITY % ENTY SYSTEM "T15n0605.ent">
<!ENTITY % CBENT SYSTEM "../dtd/cbeta.ent">
%ENTY;
%CBENT;
]>
<TEI.2>
<teiHeader>
	<fileDesc>
		<titleStmt>
			<title>Taisho Tripitaka, Electronic version, No. 0605 禪行法想經</title>
			<author>後漢 安世高譯</author>
			<respStmt>
				<resp>Electronic Version by</resp>
				<name>CBETA</name>
			</respStmt>
		</titleStmt>
	<editionStmt>
		<edition>$Revision: 1.11 $ (Big5)<date>$Date: 2012/08/27 03:14:58 $</date>新式標點版</edition>
	</editionStmt>
	<extent>1卷</extent>
	<publicationStmt>
		<distributor>
			<name>中華電子佛典協會 (CBETA)</name>
			<address>
				<addrLine>service@cbeta.org</addrLine>
			</address>
		</distributor>
		<availability>
			<p>Available for non-commercial use when distributed with this header intact.</p>
		</availability>
		<date>$Date: 2012/08/27 03:14:58 $</date>
	</publicationStmt>
	<sourceDesc>
		<bibl>Taisho Tripitaka Vol. 15, No. 605 &desc;</bibl>
	</sourceDesc>
</fileDesc>
<encodingDesc>
	<projectDesc>
		<p lang="eng" type="ly">Text as provided by Mr. Hsiao Chen-Kuo, Text as provided by Mr. Christian Wittern, Text as provided by SAT, Japan, Text as provided by Anonymous, USA, Punctuated text as provided by Mr. Ji Ge Ai Nuo</p>
		<p lang="chi" type="ly">蕭鎮國大德提供，維習安大德提供，日本 SAT 組織提供，北美某大德提供，吉格艾諾提供新式標點</p>
	</projectDesc>
</encodingDesc>
<profileDesc>
		<langUsage>
			<language id="eng">English</language>
			<language id="chi">Chinese</language>
		</langUsage>
	</profileDesc>
	<revisionDesc>
	<change>
		<date>19991011/23:56:07</date>
		<respStmt><name>CW</name><resp>ed.</resp></respStmt>
		<item>Created initial TEI XML version with BASICX.BAT (99/10/12)</item>
	</change>
<!--
$Log: T15n0605.xml,v $
Revision 1.11  2012/08/27 03:14:58  maha
修訂新標小圓點及著重號

Revision 1.10  2011/09/15 05:46:53  eva
上傳 新式標點版

Revision 1.9  2009/04/23 07:58:51  amtbgrace
modified: 檔頭編碼由 big5 改為 cp950。

Revision 1.8  2006/04/12 21:54:56  saywhat
lem 加 wit 屬性，p, lg, item 第二次加 id 屬性

Revision 1.6  2004/10/11 23:56:36  saywhat
段落前加入圈點

Revision 1.5  2004/09/13 14:17:03  saywhat
<trailer> => <juan fun="close"><jhead>

Revision 1.4  2004/04/20 08:38:10  maha
「版本日期」標記修訂

Revision 1.3  2003/06/19 03:44:38  eva
modified: 插入星號校勘

Revision 1.2  2003/05/05 06:23:10  eva
modified

Revision 1.16  2002/12/05 12:30:40  eva
modified

Revision 1.15  2002/11/04 10:41:11  ray
tei.2 => TEI.2

Revision 1.14  2002/10/07 13:07:34  moved
modified

Revision 1.13  2002/07/29 09:54:42  vinking
modified lang

Revision 1.12  2002/04/04 07:44:15  ray
xml:stylesheet => xml-stylesheet

Revision 1.11  2001/07/27 07:11:29  ray
去除多餘的 <author>

Revision 1.10  2001/07/24 06:51:17  ray
add 作者、譯者 <author> 卷數 <extent>

Revision 1.9  2001/05/25 08:56:15  ray
經號統一為四碼

Revision 1.8  2001/03/30 05:43:38  ray
缺字CB碼由四碼增長為五碼

Revision 1.7  2001/03/25 09:03:43  ray
add <milestone>

Revision 1.6  2001/02/07 06:50:19  chris
Fixed problem with comment in the previous checkin

Revision 1.5  2001/02/03 07:39:48  chris
Added keywords $Revision: 1.11 $, $Date: 2012/08/27 03:14:58 $ and $Log.
Added comment  for Emacs

-->
 </revisionDesc>
</teiHeader>
<text><body>
<lb n="0181b14" ed="T"/>
<milestone n="1" unit="juan"/>
<lb n="0181b15" ed="T"/>
<lb n="0181b16" ed="T"/><head type="no">No. 605</head>
<lb n="0181b17" ed="T"/><juan n="001" fun="open"><mulu n="001" type="卷"/><jhead><title>禪行法想經</title></jhead></juan>
<lb n="0181b18" ed="T"/>
<lb n="0181b19" ed="T"/><byline type="Translator">後漢<note n="0181008" resp="Taisho" type="orig" place="foot text">〔安息國〕－【宋】【元】【宮】</note><app n="0181008"><lem wit="【大】">安息國</lem><rdg resp="Taisho" wit="【宋】【元】【宮】">&lac;</rdg></app>三藏安世高譯</byline>
<lb n="0181b20" ed="T"/><div1 type="jing"><p id="pT15p0181b2001">聞如是：</p><p id="pT15p0181b2004" place="inline">一時，佛遊於<note n="0181009" resp="Taisho" type="orig" place="foot text">舍衛＋（國）【三】</note><note n="0181009" resp="CBETA" type="mod">舍衛＋（國）【宋】【元】【明】</note><app n="0181009"><lem wit="【大】">舍衛</lem><rdg resp="Taisho" wit="【宋】【元】【明】">舍衛國</rdg></app>祇樹給孤獨園。佛
<lb n="0181b21" ed="T"/>告：「諸比丘！」比丘受教，從佛而聽。</p><p id="pT15p0181b2113" place="inline">佛言：「諸比丘！
<lb n="0181b22" ed="T"/>若以彈指間，思惟死想，念有身皆死，是為精
<lb n="0181b23" ed="T"/>進行禪，為如佛教，不是愚癡食國人施也，何
<lb n="0181b24" ed="T"/>況多行者！取要言之，若念不淨想、穢食想、一
<lb n="0181b25" ed="T"/>切世間無有樂想、無常想、無常為<note n="0181010" resp="Taisho" type="orig" place="foot text">苦＝若【明】＊</note><app n="0181010"><lem wit="【大】">苦</lem><rdg resp="Taisho" wit="【明】">若</rdg></app>想、<app type="＊" source="0181010"><lem wit="【大】">苦</lem><rdg resp="Taisho" wit="【明】">若</rdg></app>
<lb n="0181b26" ed="T"/>為非身想、非身為空想、棄離想、&CB00230;婬想、滅盡
<lb n="0181b27" ed="T"/>想、無我想；身死為蟲食想、血流想、&CB00167;脹想、
<lb n="0181b28" ed="T"/>青腐想、糜爛腥臭想、髮落肉盡想、一切縛解
<lb n="0181b29" ed="T"/>想、骨節分散想、骨變赤白枯黑亦如鳩色想、
<pb n="0181c" ed="T" id="T15.0605.0181c"/>
<lb n="0181c01" ed="T"/>骨糜為灰想、世間無所歸想、世間無牢固想、
<lb n="0181c02" ed="T"/>世間為別離想、世間闇冥想、世間難忍想、世
<lb n="0181c03" ed="T"/>為費耗不中用想、世為災變可患厭想、一切
<lb n="0181c04" ed="T"/>世間歸泥洹想。</p><p id="pT15p0181c0407" place="inline">「諸比丘，若以彈指間念此諸
<lb n="0181c05" ed="T"/>想之事，皆為精進行，為奉佛教，不是愚癡食
<lb n="0181c06" ed="T"/>人施也，何況能多行！是故可念行法想。」</p><p id="pT15p0181c0616" place="inline">佛說
<lb n="0181c07" ed="T"/>是已，皆歡喜受。</p></div1>
<lb n="0181c08" ed="T"/><juan n="001" fun="close"><jhead><title>禪行法想經</title></jhead></juan>
</body></text></TEI.2>
